/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module answer_key_module_5 (
    input [1:0] current_step,
    input [15:0] current_map,
    output reg [1:0] lrud
  );
  
  
  
  always @* begin
    lrud = 4'bxxxx;
    if (current_step == 1'h1) begin
      lrud = current_map[10+1-:2];
    end else begin
      if (current_step == 2'h2) begin
        lrud = current_map[8+1-:2];
      end else begin
        if (current_step == 2'h3) begin
          lrud = current_map[6+1-:2];
        end else begin
          if (current_step == 3'h4) begin
            lrud = current_map[4+1-:2];
          end else begin
            if (current_step == 3'h5) begin
              lrud = current_map[2+1-:2];
            end else begin
              if (current_step == 3'h6) begin
                lrud = current_map[0+1-:2];
              end
            end
          end
        end
      end
    end
  end
endmodule
