/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module led_module_2 (
    output reg led0,
    output reg led1,
    output reg led2,
    output reg led3,
    output reg led4,
    output reg led5,
    output reg led6,
    output reg led7,
    output reg led8,
    output reg led9,
    output reg led10,
    output reg led11,
    output reg led12,
    output reg led13,
    output reg led14,
    output reg led15,
    input [15:0] reg_led
  );
  
  
  
  always @* begin
    led0 = reg_led[0+0-:1];
    led1 = reg_led[1+0-:1];
    led2 = reg_led[2+0-:1];
    led3 = reg_led[3+0-:1];
    led4 = reg_led[4+0-:1];
    led5 = reg_led[5+0-:1];
    led6 = reg_led[6+0-:1];
    led7 = reg_led[7+0-:1];
    led8 = reg_led[8+0-:1];
    led9 = reg_led[9+0-:1];
    led10 = reg_led[10+0-:1];
    led11 = reg_led[11+0-:1];
    led12 = reg_led[12+0-:1];
    led13 = reg_led[13+0-:1];
    led14 = reg_led[14+0-:1];
    led15 = reg_led[15+0-:1];
  end
endmodule
