/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module button_module_6 (
    input button0,
    input button1,
    input button2,
    input button3,
    input button4,
    input button5,
    input button6,
    input button7,
    output reg player,
    output reg [1:0] lrud
  );
  
  
  
  always @* begin
    player = 4'bxxxx;
    lrud = 4'bxxxx;
    if (button0 == 1'h1) begin
      player = 1'h0;
      lrud = 2'h0;
    end else begin
      if (button1 == 1'h1) begin
        player = 1'h0;
        lrud = 2'h1;
      end else begin
        if (button2 == 1'h1) begin
          player = 1'h0;
          lrud = 2'h2;
        end else begin
          if (button3 == 1'h1) begin
            player = 1'h0;
            lrud = 2'h3;
          end else begin
            if (button4 == 1'h1) begin
              player = 1'h1;
              lrud = 2'h0;
            end else begin
              if (button5 == 1'h1) begin
                player = 1'h1;
                lrud = 2'h1;
              end else begin
                if (button6 == 1'h1) begin
                  player = 1'h1;
                  lrud = 2'h2;
                end else begin
                  if (button7 == 1'h1) begin
                    player = 1'h1;
                    lrud = 2'h3;
                  end
                end
              end
            end
          end
        end
      end
    end
  end
endmodule
