/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module button_module_6 (
    input [2:0] button,
    output reg player,
    output reg [1:0] lrud
  );
  
  
  
  always @* begin
    player = 4'bxxxx;
    lrud = 4'bxxxx;
    if (button == 3'h0) begin
      player = 1'h0;
      lrud = 2'h0;
    end else begin
      if (button == 3'h1) begin
        player = 1'h0;
        lrud = 2'h1;
      end else begin
        if (button == 3'h2) begin
          player = 1'h0;
          lrud = 2'h2;
        end else begin
          if (button == 3'h3) begin
            player = 1'h0;
            lrud = 2'h3;
          end else begin
            if (button == 3'h4) begin
              player = 1'h1;
              lrud = 2'h0;
            end else begin
              if (button == 3'h5) begin
                player = 1'h1;
                lrud = 2'h1;
              end else begin
                if (button == 3'h6) begin
                  player = 1'h1;
                  lrud = 2'h2;
                end else begin
                  if (button == 3'h7) begin
                    player = 1'h1;
                    lrud = 2'h3;
                  end
                end
              end
            end
          end
        end
      end
    end
  end
endmodule
