/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module check_step_module_4 (
    input lrud_player,
    input lrud_answer,
    output reg out
  );
  
  
  
  wire [16-1:0] M_alu_answer;
  wire [1-1:0] M_alu_n;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_z;
  reg [16-1:0] M_alu_firstNumber;
  reg [16-1:0] M_alu_secondNumber;
  reg [6-1:0] M_alu_alufn;
  new_alu_1 alu (
    .firstNumber(M_alu_firstNumber),
    .secondNumber(M_alu_secondNumber),
    .alufn(M_alu_alufn),
    .answer(M_alu_answer),
    .n(M_alu_n),
    .v(M_alu_v),
    .z(M_alu_z)
  );
  
  always @* begin
    out = 4'bxxxx;
    M_alu_firstNumber = lrud_player;
    M_alu_secondNumber = lrud_answer;
    M_alu_alufn = 6'h24;
    out = M_alu_answer[0+0-:1];
  end
endmodule
