/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module check_player_module_3 (
    output reg check_player,
    input answer_player,
    input player
  );
  
  
  
  wire [16-1:0] M_alu_answer;
  wire [1-1:0] M_alu_n;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_z;
  reg [16-1:0] M_alu_firstNumber;
  reg [16-1:0] M_alu_secondNumber;
  reg [6-1:0] M_alu_alufn;
  new_alu_1 alu (
    .firstNumber(M_alu_firstNumber),
    .secondNumber(M_alu_secondNumber),
    .alufn(M_alu_alufn),
    .answer(M_alu_answer),
    .n(M_alu_n),
    .v(M_alu_v),
    .z(M_alu_z)
  );
  
  always @* begin
    check_player = 4'bxxxx;
    M_alu_firstNumber = player;
    M_alu_secondNumber = answer_player;
    M_alu_alufn = 6'h33;
    check_player = M_alu_answer[0+0-:1];
  end
endmodule
